---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "backend-v1"
  annotations:
    description: "Template for backend-v1 deployment and service"
labels:
  template: "backend-v1-template"
objects:
  - kind: "Service"
    apiVersion: "v1"
    metadata:
      name: "$(BACKEND_V1_NAME)"
      namespace: "$(BACKEND_V1_NAMESPACE)"
    spec:
      selector:
        app: "$(BACKEND_V1_NAME)"
      ports:
        - protocol: "TCP"
          port: $((BACKEND_V1_SERVICE_PORT))
          targetPort: $((BACKEND_V1_CONTAINER_PORT))
  - kind: "Deployment"
    apiVersion: "apps/v1"
    metadata:
      name: "$(BACKEND_V1_NAME)"
      namespace: "$(BACKEND_V1_NAMESPACE)"
    spec:
      replicas: $((BACKEND_V1_REPLICAS))
      selector:
        matchLabels:
          app: "$(BACKEND_V1_NAME)"
      template:
        metadata:
          labels:
            app: "$(BACKEND_V1_NAME)"
        spec:
          containers:
            - name: "$(BACKEND_V1_CONTAINER_NAME)"
              image: "$(BACKEND_V1_CONTAINER_IMAGE)"
              ports:
                - containerPort: $((BACKEND_V1_CONTAINER_PORT))
              resources:
                requests:
                  memory: "$(BACKEND_V1_CONTAINER_REQUESTS_MEMORY)"
                  cpu: "$(BACKEND_V1_CONTAINER_REQUESTS_CPU)"
                limits:
                  memory: "$(BACKEND_V1_CONTAINER_LIMITS_MEMORY)"
                  cpu: "$(BACKEND_V1_CONTAINER_LIMITS_CPU)"
parameters:
  - name: "BACKEND_V1_NAME"
    description: "Name of the backend-v1 service and deployment"
    required: true
    parameterType: "string"
  - name: "BACKEND_V1_NAMESPACE"
    description: "Namespace for backend-v1"
    required: true
    parameterType: "string"
  - name: "BACKEND_V1_REPLICAS"
    description: "Number of replicas for backend-v1"
    required: true
    parameterType: "int"
  - name: "BACKEND_V1_CONTAINER_NAME"
    description: "Container name"
    required: true
    parameterType: "string"
  - name: "BACKEND_V1_CONTAINER_IMAGE"
    description: "Container image"
    required: true
    parameterType: "string"
  - name: "BACKEND_V1_CONTAINER_PORT"
    description: "Container port"
    required: true
    parameterType: "int"
  - name: "BACKEND_V1_CONTAINER_REQUESTS_MEMORY"
    description: "Memory requests"
    required: true
    parameterType: "string"
  - name: "BACKEND_V1_CONTAINER_REQUESTS_CPU"
    description: "CPU requests"
    required: true
    parameterType: "string"
  - name: "BACKEND_V1_CONTAINER_LIMITS_MEMORY"
    description: "Memory limits"
    required: true
    parameterType: "string"
  - name: "BACKEND_V1_CONTAINER_LIMITS_CPU"
    description: "CPU limits"
    required: true
    parameterType: "string"
  - name: "BACKEND_V1_SERVICE_PORT"
    description: "Service port"
    required: true
    parameterType: "int" 