[build]
builder = "DOCKERFILE"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Service configurations
[[services]]
name = "backend-v1"
port = 8080

[[services]]
name = "backend-v2"
port = 8080
