apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - name: curl
        image: curlimages/curl:8.2.1
        command: ["sh", "-c", "for i in $(seq 1 1000); do curl -s myapp.default:8181/ 2>/dev/null; sleep 1; done"] 