---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  strategy:
    type: Recreate
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ghcr.io/koumi15cancer/deployment_demo/backend-v1:latest
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SERVICE_NAME
              value: "backend-v1"
            - name: SERVICE_VERSION
              value: "1.0"
            - name: PORT
              value: "8080"
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
