name: Build and Deploy to Railway

on:
  push:
    branches: [ main, master ]
    paths:
      - 'backend/**'
      - '.github/workflows/railway-deploy.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy-backend-v1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend-v1
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/backend-v1:latest
          build-args: |
            SERVICE_NAME=backend-v1
            SERVICE_VERSION=1.0

      - name: Install Railway CLI
        uses: railwayapp/cli-action@v1
        with:
          token: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy backend-v1 to Railway
        run: |
          railway up --service backend-v1 --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  build-and-deploy-backend-v2:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend-v2
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/backend-v2:latest
          build-args: |
            SERVICE_NAME=backend-v2
            SERVICE_VERSION=2.0

      - name: Install Railway CLI
        uses: railwayapp/cli-action@v1
        with:
          token: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy backend-v2 to Railway
        run: |
          railway up --service backend-v2 --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
